### ISSUE TITLE
[Suggestion / Feedback] Aluminum Generation Settings

### ISSUE THREAD

**Issue by MadSciSlack** [northwesttrees-gaming/CCTVCraft-Forge#33]
Although I really liked this mod and wanted to keep it in my pack, the sheer amount of aluminum that generates in world is way too much.  The lack of a config means that I couldn't balance this with other ore generations.  Aluminum also doesn't work like regular metals either, so using some of the excess for pickaxes etc isn't an option.

Other aluminum types also don't work with CCTV Craft's recipes, as most don't seem to be done with Forge tags.  Between this, the early game buildup of aluminum, aluminum taking valuable worldgen space from other ores, and the lack of configurability; I've had no choice but to steer away from your mod.

This mod would otherwise fit beautifully in my modpack.  It's a great mod overall.  I hope you find this feedback useful for your future development.  Feel free to delete this feedback issue when it's outlived its usefulness.

Cheers,

Slack

**Comment by Gamerbolts** [comment]
I would agree with this as well. I had put this in my modpack and the amount of Aluminum ore that spawn was insane. Please create a config that would allow us to tone it down or disable ore gen. Thanks!

**Comment by northwesttreesgaming** [comment]
I have had to roll back before the sound update was added due to the performance for drones with this version being so bad so I will do my best to address the issues as aluminum ore was not added yet in the version I rolled back to.

Below is just for me to keep track of what I need to do.
- [ ] Lower Aluminum Ore amount with generation.
- [ ] Set up tags for "forge:ores/aluminum", "forge:ingots/aluminum", "forge:nuggets/aluminum", and "forge:gear/aluminum"
- [ ] Add aluminum tool and armour set.

**Comment by northwesttreesgaming** [comment]
# Config File Settings
So the Ore config file can be changed while in-game.
It's located under config/cctvcraft/ore_distribution.json
There are three settings I could set up.

1. "min_y" which controls the minimum Y generation level.
  - This value can be the same or below "max_y"
  - The lowest value is -64 for this value.
  - The highest value is 320 for this value.
  - If the values are over the highest and lowest limits then it will set it to the nearest limit value.
    - Example 1: if max_y is set to 330 then it will be set to 320
    - Example 2: if min_y is set to -128 then it will be set to -64
2. "max_y" which controls the maximum Y generation level
  - If "min_y" is over "max_y" then "min_y" is set to "max_y"
  - The lowest value is -64 for this value.
  - The highest value is 320 for this value.
  - If the values are over the highest and lowest limits then it will set it to the nearest limit value.
    - Example 1: if max_y is set to 330 then it will be set to 320
    - Example 2: if min_y is set to -128 then it will be set to -64
3. "chance" which controls the chance of it generating.
  - The value ranges from 1 to 100
  - Aluminum ore has a default value of 10 which
  - Math: Random [1 ~ 100] ≤ "chance"
  - Setting the chance to a lower number will make the ore generated less common.
  - Setting the chance to a higher value will make the other genre more common.

# Generation
Ore generation size is not set to 14 using a uniform generation type which should help with mod customizability.
The frequency per chunk can be controlled using "chance" This is a value out of 1 - 100 as mentioned above so see it as 1 per chunk. Default is 10

# Generation Tags
- "cctvcraft:aluminum_ore_can_replace" block tag allows for overrides for what blocks the ore can replace.
- "cctvcraft:ores/aluminum" biome tag allows for overrides for what biomes the ore can generate in.
- "forge:ores/aluminum" both blocks are under this tag.

# Blocks
Giving that I just said both blocks I should note that I needed to make an unused block for the generation placement condition that could allow for the "min_y" and "max_y" values to be tested for as feature placement conditions don't support testing the height, this was a workaround to allow these two settings to work. other than that the block is not used for anything other than the proxy placement condition which is used in generation.

# Forge Tags
I am still working on setting up the forge tag support, this is going to take some time to do but will get done in the next couple of weeks for sure. Once this is done I will add the armor and tools and wrap up by adding the sound update features which I had to readd to the mod.

The internal release.

But hopefully, this will give you guys more options for mod-packs.

**Comment by northwesttreesgaming** [comment]
Added
- Aluminum Armor
- Aluminum Axe
- Aluminum Fishing Rod
- Aluminum Hoe
- Aluminum Pickaxe
- Aluminum Shovel
- Aluminum Sword

Armour is a bit less than iron armour for its value I looked up the mohs and it's 2.75 compared to iron which is 4. So I tried to keep it around that range for its settings.
