### ISSUE TITLE
[Bug] ore can't be mined with custom pickaxes (Example Tetra)

### ISSUE THREAD

**Issue by GD12919** [northwesttrees-gaming/CCTVCraft-Forge#38]
### Current Behavior

Issue is that using modular pickaxes, like in tetra mod.. when using a pickaxe it should be dropping the ore but instead it doesn't drop.

Saw a similar issue as this is related to MCreator for some reason

Tetra dev said

"From what I've gathered the "correct" way to handle tool requirements is for blocks that require a pickaxe to break to be tagged with "minecraft:mineable/pickaxe", and tetra tools relies on that. Both of the mods you've references appear to be made with mccreator, I don't know how that works. Closing."

I'm not sure if this is fixable using a datapack, but i have no clue.

### Mod Build

4.7.0

### Minecraft Release

1.20.1

**Comment by northwesttreesgaming** [comment]
Pretty sure this would have to do with the tool you used not being high enough on the harvest level as all necessary tags to break blocks are applied automatically. Depending on what block you were trying to break it may have needed a higher harvest level. For example, if you mine diamond ore with a wooden pickaxe it will break the block with no drops. My best guess is this is what is happening with the tool you used, most likely not high enough on the harvest level to break the block you tried to mine.

If this is the case then there is nothing I can do on my end as it would require the mod in question to change their tools to work with higher harvest levels. They may be able to add support for new tools with higher harvest levels but again this would be up to the developer. If there are already options in the mod then try breaking the block with different third tools if the mod already has support.

I will leave this issue open for now and mark it as information needed.
Let me know if this is the problem so I can close the issue.
