### ISSUE TITLE
[Bug] <Drones are unmovable>

### ISSUE THREAD

**Issue by IanCavalluzzi** [northwesttrees-gaming/CCTVCraft-Forge#40]
### Current Behavior

Drones will not move or fly. 

You can access drones and use inventory, actions, and turning keys, but when attempting to fly drones you will rubber band and not move.

If you are trying to move in the direction of a block you will sometimes you will receive the "Drone is Blocked" message.

### Mod Build

4.7.0

### Minecraft Release

1.20.1

**Comment by northwesttreesgaming** [comment]
This has been fixed in the next release that I am working on I closed the issue in #35
