### ISSUE TITLE
can you make it open source please?

### ISSUE THREAD

**Issue by Wayasho** [northwesttrees-gaming/CCTVCraft-Forge#42]
### Suggestion or Feature

make the mod open source,.

### Core Features

please

### Reason For Feature

Trying to edit recipes with datapacks for my modpack (which i will not upload to forge, it is for me and my friends).

**Comment by northwesttreesgaming** [comment]
Datapack wise you don't need the source code all you need is to open the jar with 7zip and grab the data folder.
Keep the path the same and it should allow you to change the mod recipes without any issues.
Giving you set up the data pack correctly that is.

I have a tutorial on my channel on how to open up the Minecraft jar, the same process and then just follow the wiki steps for making a data pack. That simply works for any mod like this. No need to have the source code to make data packs.
