### ISSUE TITLE
my drone have blocked how to use it

### ISSUE THREAD

**Issue by mui34567890** [northwesttrees-gaming/CCTVCraft-Forge#43]
### Current Behavior

i cant move it 

### Mod Build

4.7

### Minecraft Release

1.20.1

**Comment by northwesttreesgaming** [comment]
This was already reported and I have found the cause and applied fixes on the version I am working on.
Though it's not public yet because I have other changes I still need to do and test the rest of the mods features to ensure they work correctly.

This was the issue reported #35
